In [12]:
from altaipony.lcio import from_mast
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
pd.set_option('display.float_format', lambda x: '%.5f' % x)
%matplotlib inline

In [72]:
dfk = pd.read_csv("C:\Vs_code_projects\mdwarf_flares\K2_catalogue_degrees.csv")
dft = pd.read_csv("C:\Vs_code_projects\mdwarf_flares\TESS_catalogue_degrees_cut.csv")

<>:1: DeprecationWarning: invalid escape sequence '\V'
<>:2: DeprecationWarning: invalid escape sequence '\V'
<>:1: DeprecationWarning: invalid escape sequence '\V'
<>:2: DeprecationWarning: invalid escape sequence '\V'
C:\Users\thoma\AppData\Local\Temp\ipykernel_13360\964684316.py:1: DeprecationWarning: invalid escape sequence '\V'
  dfk = pd.read_csv("C:\Vs_code_projects\mdwarf_flares\K2_catalogue_degrees.csv")
C:\Users\thoma\AppData\Local\Temp\ipykernel_13360\964684316.py:2: DeprecationWarning: invalid escape sequence '\V'
  dft = pd.read_csv("C:\Vs_code_projects\mdwarf_flares\TESS_catalogue_degrees_cut.csv")

In [78]:
dfk.drop(columns = ['Unnamed: 0'], inplace = True)

In [67]:
dft = dft.drop(dft.columns[-1], axis=1)

In [79]:
dfk

,EPIC ID,Teff,logg,Flare #,Observation time,Average flare duration,Longest flare duration,Shortest flare duration,Average percentage increase,Highest percentage increase,Lowest percentage increase,Flares per hour,Flares per day,RA,Dec
0,248526013,4142.83740,4.63070,3.00000,79.66369,0.16346,0.18389,0.14302,0.17469,0.23472,0.13415,0.00157,0.03766,153.42055,3.91169
1,213508874,4212.15970,4.46730,5.00000,81.33884,0.38003,1.49153,0.10216,2.16091,7.36572,0.57856,0.00256,0.06147,286.20681,-29.17696
2,220231988,4036.32060,4.62530,4.00000,78.68262,0.12259,0.22475,0.08173,0.12058,0.16385,0.08435,0.00212,0.05084,18.84456,1.12372
3,245921548,4233.24300,4.54960,34.00000,78.86645,0.17788,0.49036,0.08173,2.14408,3.48939,0.97145,0.01796,0.43111,352.72547,-12.16080
4,246773415,4128.93260,4.37020,2.00000,80.54210,0.13281,0.14302,0.12259,7.15487,10.03917,4.27057,0.00103,0.02483,75.20543,15.44993
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3237,220231660,3876.68650,4.79620,4.00000,78.68262,0.21453,0.32690,0.12259,8.50663,11.98218,5.29402,0.00212,0.05084,18.71013,1.11238
3238,248474210,3344.35230,4.89570,1.00000,79.66382,0.12259,0.12259,0.12259,4.88849,4.88849,4.88849,0.00052,0.01255,157.73781,2.30446
3239,220222734,3989.65600,4.78130,2.00000,78.68268,0.09194,0.10216,0.08173,6.16190,6.50280,5.82100,0.00106,0.02542,20.61833,0.80299
3240,245944800,4232.94600,4.76100,1.00000,78.86638,0.12259,0.12259,0.12259,5.72118,5.72118,5.72118,0.00053,0.01268,349.59896,-11.02842
3241,201217829,3601.87040,4.63060,0.00000,79.97015,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,169.24339,-3.69785

In [14]:
columns = ['Unnamed: 0', 'TIC ID', 'Teff', 'logg', 'Flare #', 'Observation time', 'Average flare durartion', 'Longest flare duration', 'Shortest flare duration', 'Average percentage increase', 'Highest percentage increase', 'Lowest percentage increase', 'Flares per hour', 'Flares per day', 'RA', 'Dec']
empty = pd.DataFrame(columns = columns, index = range(2150, 3242))
dft = pd.concat([dft, empty])

C:\Users\thoma\AppData\Local\Temp\ipykernel_13360\3761300787.py:3: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  dft = pd.concat([dft, empty])

In [75]:
def remove_last_decimal(x):
    if pd.notnull(x):
        return int(x * 10**5) / 10**5
    else:
        return x

In [82]:
dft['Dec'] = dft['Dec'].apply(remove_last_decimal)

In [84]:
dft.to_csv("C:\Vs_code_projects\mdwarf_flares\TESS_catalogue_degrees_cut.csv", index = False)

<>:1: DeprecationWarning: invalid escape sequence '\V'
<>:1: DeprecationWarning: invalid escape sequence '\V'
C:\Users\thoma\AppData\Local\Temp\ipykernel_13360\2147527219.py:1: DeprecationWarning: invalid escape sequence '\V'
  dft.to_csv("C:\Vs_code_projects\mdwarf_flares\TESS_catalogue_degrees_cut.csv", index = False)

In [ ]:
for i in len()